PORI-270: Only show relevant target audiences in the news archive
City-of-Pori/pori-kada pull request #163
Opened 2018-02-12 10:10 UTC by ZeiP

drush fra -y

/news-archive should only show relevant taxonomy terms as filter options for target audience.

2018-02-12 11:56 UTC, teroelonen requested changes
This works for pori.fi but now visitpori.fi shows only pori.fi target audiances.

2018-02-13 12:35 UTC, ZeiP commented
Visitpori.fi news archive is in PORI-299, so IMO this can be merged if there are no other concerns.

2018-02-14 13:03 UTC, ZeiP commented
I decided to add the VisitPori news archive to the same branch, should work now.

2018-02-23 13:11 UTC, teroelonen approved these changes

2018-02-23 13:11 UTC, merged